version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - gosec
    - misspell
    - nilerr
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    gosec:
      excludes:
        - G104
        - G304
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-naming
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
